FROM node:16-alpine
ARG BOT_TOKEN=${BOT_TOKEN}
ENV BOT_TOKEN=${BOT_TOKEN}
ARG TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
ENV TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
ENV PORT 80
EXPOSE 80
CMD ["node", "server.js"]